config/routes.rb
EmotionForm::Application.routes.draw do
  post "questions/answer"
  resources :questions
  get "report" => 'report#to_csv'

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/answer.rb
class Answer
  include Mongoid::Document
  include Mongoid::Timestamps

  field :text, type: String
  embedded_in :question
  belongs_to :user
  validates :user, presence: true
  validates :text, presence: true
end

app/models/question.rb
class Question
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :type, type: String, default: 'text'

  field :options, type: Array

  embeds_many :answers
  validates :name, presence: true
  validates :type, inclusion: ['text', 'scale'], presence: true

  def save_answer(answer, current_user)
    self.answers.create text: answer, user: current_user
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  validates_presence_of :email
  validates_presence_of :encrypted_password
  
  field :admin, type: Boolean, default: false
  
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
  # run 'rake db:mongoid:create_indexes' to create indexes
  index({ email: 1 }, { unique: true, background: true })
  field :name, :type => String
  validates_presence_of :name
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :created_at, :updated_at
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!

  def only_admin
    if current_user.admin
      true
    else
      redirect_to root_path, alert: "Nur Admins erlaubt."
      false
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @questions = Question.all.asc :name
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :only_admin, except: :answer

  def answer
    params[:answers].each do |key, value|
      Question.find(key).save_answer(value, current_user)
    end
    redirect_to root_path, notice: "Dankeschoen!"
  end

  def show
    @question = Question.find params[:id]
  end

  def new
  	@question = Question.new
  end

  def create
  	@question = Question.new params[:question]

    set_options @question, params[:options]

  	if @question.save
  		redirect_to @question, notice: "Die Frage wurde erstellt."
  	else
  		render action: :new
  	end
  end

  def edit
		@question = Question.find params[:id]
  end

  def update
  	@question = Question.find params[:id]
    set_options @question, params[:options]

    if @question.update_attributes params[:question]
      redirect_to @question, notice: "Die Frage wurde gespeichert."
    else
      render action: :edit
    end
  end

  def index
      @questions = Question.all
  end

  def destroy
    @question = Question.find params[:id]
    @question.destroy
    redirect_to questions_path, notice: "Die Frage wurde geloescht."
  end

  protected
  def set_options(question, options)
    options_arr = options.split(',').map do |option|
      option.strip unless option.strip.blank?
    end
    question.options = options_arr.compact
  end
end

app/controllers/report_controller.rb
require 'csv'

class ReportController < ApplicationController
  before_filter :authenticate_user!, :only_admin
	def to_csv
		@questions = Question.all

		csv_data = CSV.generate do |csv|

			csv << ['Fragen-ID', 'Timestamp ID', 'Benutzer', 'Zeit', 'Frage', 'Antwort']

			@questions.each do |question|
				question.answers.each do |answer|
					timestamp_id = Digest::SHA1.hexdigest(answer.created_at.to_s + answer.user.id.to_s)

					csv << [question.id, timestamp_id, answer.user.id, answer.created_at, question.name, answer.text]
				end
			end

		end

		send_data csv_data, :type => 'text/csv', :filename => 'report_'+Time.current.to_s.tr(" ", "_")

	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h3>Home</h3>
<% if @questions.any? %>
<%= form_tag questions_answer_path %>
<% @questions.each do |question| %>
  <p>
	<strong><%= link_to_if current_user.try(:admin), question.name, question %></strong>
	<br>
	<% if question.type == 'text' %>
	<input name="answers[<%= question.id %>]" id="answers_<%= question.id %>" placeholder="Antwort">
	<% else %>
	<ul class="radio-group clearfix">
		<% question.options.each do |option| %>
		<li>
			<%= radio_button_tag "answers[#{question.id}]", option %>
			<label><%= option %></label>
		</li>
		<% end %>
	</ul>
	<% end %>
  </p>
<% end %>
<%= submit_tag "OK", class: 'btn btn-primary' %>
</form>
<% else %>
	<p>Es existieren keine Fragen.</p>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Emotion Form", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Kontoeinstellungen', edit_user_registration_path %>
    </li>
      <% if current_user.admin %>
       <li>
        <%= link_to 'Fragen', questions_path %>
        </li>
        <% end %>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>

  <% if user_signed_in? %>
      <li>
        <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
      </li>
  <% else %>
      <li>
        <%= link_to 'Login', new_user_session_path %>
      </li>
  <% end %>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Emotion Form" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Emotion Form" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </div>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/questions/_form.html.erb
<%= simple_form_for question do |q| %>
	<%= q.input :name %>
	<%= q.input :type, collection: [['Freitext', 'text'], ['Skala', 'scale']], prompt: false %>
	<div class="control-group string required <%= question.type == 'text'? 'hide': '' %>" id="scale_options">
	<label for="options">Auswahlmöglichkeiten</label>
	<%= text_field_tag 'options', question.options.try(:join, ', ') %>
	<small class="help-block">Bitte Antwortmöglichkeiten mit Komma getrennt angeben</small>
	</div>
	<%= q.button :submit %>
<% end %>

app/views/questions/edit.html.erb
<%= render  partial: "form", locals: {question: @question} %>

app/views/questions/index.html.erb
<h3>Questions</h3>
<p> <%= link_to 'Fragen erstellen', new_question_path, class: 'btn' %>   <%= link_to '<i class="icon-file"></i> Antworten als CSV'.html_safe, report_path, class: 'btn' %> </p>
<table class="table">
	<tr>
		<th>Frage</th>
		<th>Antworten</th>
		<th>Typ</th>
		<th>Aktionen</th>
	</tr>
	<% @questions.each do |q| %>
		<tr>
			<td><%= link_to q.name, q %> </td>
			<td><%= q.answers.count %></td>
			<td><%= q.type.humanize  %></td>
			<td><%= link_to 'Editieren', edit_question_path(q), class: 'btn btn-mini' %> <%= link_to 'Löschen', q, method: 'delete', class: 'btn btn-mini btn-danger', confirm: 'Wollen Sie die Frage wirklich löschen?' %>
			</td>
		</tr>
	<% end %>
</table>

app/views/questions/new.html.erb
<%= render  partial: "form", locals: {question: @question} %>

app/views/questions/show.html.erb
<h3><%= @question.name %></h3>
<table class="table">
	<tr>
		<th>Benutzer</th>
		<th>Antwort</th>
	</tr>
	<% @question.answers.each do |answer| %>
		<tr>
			<td><%= answer.user.name %></td>
			<td><%= answer.text %></td>
		</tr>
	<% end %>
</table>

app/views/users/index.html.erb
<h3>Users</h3>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>